# -*- coding: utf-8 -*-
"""Running order for the car + hotel version. Same principle: soft blocks,
slack built in, `fix=True` only where something genuinely will not wait."""
F = lambda w, t, fix=False: dict(w=w, t=t, fix=fix)

FLOW = {
1: [
 F("≈08:00", "Ferry docks. Drive the ten minutes to the hotel and drop the bags — but your room will not be ready. Check-in here is from three.", True),
 F("Morning", "Leave the car for the whole day. Terra Vecchia on foot, the Vieux Port under the bell towers, up to the Citadelle."),
 F("Lunch", "On the Vieux Port. You have nowhere to be."),
 F("Afternoon", "Now take the car north on the D80: Erbalunga's tower around three, and a swim at Marine de Sisco if it is warm."),
 F("From 15:00", "Room is ready whenever you come back for it. Collect the key, shower off the ferry.", True),
 F("Evening", "Dinner in the old town. Tomorrow is the big Cap loop."),
],
2: [
 F("Up at seven", "137 km round the whole peninsula today, and the walk wants doing before the heat."),
 F("Morning", "Drive to Macinaggio and walk the Sentier des Douaniers — the full 10 km loop, or turn at Plage de Tamarone for a swim and be back sooner."),
 F("Midday", "Round to Barcaggio for the cows on the sand, then the Moulin Mattei for both coasts at once."),
 F("Lunch", "Port de Centuri. Lobster. Do not economise here."),
 F("Afternoon", "South down the west side. Nonza's square tower and black shingle beach — 300 steps down, and worth every one."),
 F("Late afternoon", "Patrimonio on the way home for a tasting at one of the domaines. One glass for the driver."),
 F("By 18:00", "Back in Bastia. Same room, no bags to move.", True),
],
3: [
 F("Relaxed", "The boat sets today's shape and nothing else does."),
 F("Morning", "Drive to Saint-Florent, buy the Saleccia or Lotu tickets at the quay — the day before in high season — and look at the 1440 citadel while you wait."),
 F("Sailing", "Whatever time they give you. That is the one fixed point today.", True),
 F("The beach", "White sand behind a pine forest in the middle of a desert. Nothing there at all, which is why it is worth the boat."),
 F("Late afternoon", "Back on land, out to Bocca di Vezzu for the Agriates in long light."),
 F("Evening", "Back to Bastia — 40 minutes — and eat somewhere you noticed on day one."),
],
4: [
 F("Bags in the car", "First move of the trip. Check out by eleven; the Balagne is the day."),
 F("Morning", "West to Plage de l'Ostriconi: 15 minutes down through the dunes to where a river meets the sea. Wilder than anything ahead of it."),
 F("Late morning", "L'Île-Rousse for the 19th-century covered market — before eleven — and the causeway out to the Pietra lighthouse."),
 F("Lunch", "Under the plane trees on the Place Paoli."),
 F("Afternoon", "Inland through the Balagne rather than along the coast: Pigna's workshops, Sant'Antonino's stone passageways and the view over the whole plain."),
 F("Late afternoon", "Plage de Bodri for a swim, ten minutes on foot from the road."),
 F("By 18:00", "Into Calvi. Check in, and use the pool.", True),
],
5: [
 F("Morning", "Calvi citadel while it is cool — park at the port and walk up. Roman roots, Genoese walls, the whole bay from the ramparts."),
 F("Late morning", "Coffee on the quay, then out through Calenzana, where the GR20 starts."),
 F("Midday", "Bonifatu. Paved road all the way to the Auberge car park."),
 F("Afternoon", "The Figarella walk — 5 km, 300 m, river then mountains — with deep green pools to swim in. Take lunch with you."),
 F("Late afternoon", "Back to Calvi and onto the pine beach for what is left of the sun."),
 F("Evening", "Dinner on the marina, citadel lit above. No bags to pack."),
],
6: [
 F("Decide at breakfast", "3¼ hours of driving plus a four-hour hike does not fit. Either leave at seven and do Monte Senino, or take the coast road slowly and do Senino tomorrow morning. Pick one."),
 F("Early", "If it is Senino: out of Calvi by 07:00, south through Galéria."),
 F("Late morning", "The trailhead is the big car park by Osani. 6 km, 500 m, four hours, steep throughout — and the Gulf of Girolata, the Gulf of Porto and Scandola all in one turn of the head."),
 F("Instead", "If not: Galéria and the Fango river pools, then the D81 taken slowly with every layby used. This is the best coast road in Corsica."),
 F("Late afternoon", "Down into Porto. Climb the Genoese tower."),
 F("By 18:00", "Check in on the marina.", True),
 F("Evening", "The Pont de Pianella is 15 minutes up the Spelunca road if the light holds."),
],
7: [
 F("Early", "In the Calanches by eight, before the coaches and the heat."),
 F("Morning", "The Château Fort loop on foot, 2.5 km. The rock shapes do not work from a car window."),
 F("Late morning", "Coffee in Piana on the church square."),
 F("Midday", "Capo Rosso: 8.5 km, 500 m, three to four hours, no shade whatsoever. Two litres each. Climb the ladder inside the tower at the end."),
 F("Afternoon", "Plage d'Arone. Swim, eat at the beach bar, do nothing."),
 F("By 17:30", "Back to Porto and check in — before the evening, not after.", True),
 F("≈21:00", "Drive fifteen minutes back for the Calanches at sunset. Orange to blood red, and empty. The room is already yours, so there is no rush home.", True),
],
8: [
 F("Check out by eleven", "Second move. Down the west coast today."),
 F("Morning", "Cargèse — a Greek Orthodox church facing a Catholic one across the same square, founded by refugees in the 18th century. Then Sagone for a swim."),
 F("Lunch", "On the water at Sagone or Tiuccia."),
 F("Afternoon", "Into Ajaccio. Park at the Diamant and walk: Maison Bonaparte, the Fesch museum's Italian paintings, the old port."),
 F("By 16:00", "Check in early today — you are going back out.", True),
 F("≈20:30", "Out to the Pointe de la Parata for the Îles Sanguinaires at sunset. Check the car park barrier time first; it often shuts before the sun does.", True),
 F("Evening", "Ajaccio is the best restaurant town on the island. Use it."),
],
9: [
 F("The empty-boot day", "No luggage, no check-out, 136 km of mountains and the same bed at the end."),
 F("Morning", "The D3 up to Lac de Tolla — narrow and twisting, laybys with lake views the whole way. Swim, or take a kayak out."),
 F("Late morning", "On to Bocognano for the Cascata di u Velu di a Spusata: 150 m down a granite face, twenty minutes' walk. Thunderous in May and June."),
 F("Lunch", "Vizzavona, at 900 m and fifteen degrees cooler than the coast."),
 F("Afternoon", "The Cascade des Anglais — 5 km round through beech and laricio forest on GR20 waymarks. The easiest beautiful walk in Corsica."),
 F("Coming home", "The D1 and D4 back towards Ajaccio: a narrow pass with unguarded edges and no traffic. Not after dark."),
 F("Evening", "Back in Ajaccio by half six. Aperitif on the Place Foch."),
],
10: [
 F("Away by nine", "139 km south, and it is worth arriving in daylight."),
 F("Late morning", "Filitosa. Carved menhirs with faces and swords, four thousand years old, in an olive grove. Ninety minutes with the museum."),
 F("Lunch", "Propriano on the water."),
 F("Afternoon", "Sartène — grey granite, vaulted passages, the most Corsican of Corsican towns. Park below the Place Porta; the old town is stairs."),
 F("Optional", "Roccapina: the track down is 3.5 km of rock, and a low hire car will ground out. Park at the top and walk 45 minutes, or admire the lion from the road and drive on."),
 F("By 18:00", "Into Bonifacio. Parking here is genuinely hard — ask the hotel where to put the car before you arrive.", True),
 F("Evening", "Up into the Haute Ville once the day boats have gone. The ramparts at dusk with Sardinia on the horizon."),
],
11: [
 F("Boat day", "Barely any driving. Decide at breakfast whether the Lavezzi are on — the morning sailing is the good one.", True),
 F("Morning", "Out to the Lavezzi: granite boulders, marine reserve, impossibly clear water. Or stay and take the 187 steps of the Escalier du Roi d'Aragon down the cliff face."),
 F("Lunch", "On the marina quay, under the town."),
 F("Afternoon", "Twenty minutes north to Rondinara — a near-circular bay, shallow and sheltered, and the best swim in the south."),
 F("Late afternoon", "Back to Bonifacio. Same room, nothing to pack."),
 F("Evening", "The clifftop viewpoints on the south side of the citadel, then dinner. Tomorrow is the long one."),
],
12: [
 F("Leave by half eight", "The heaviest day: 144 km, three beaches and a waterfall walk, finishing 900 m up in a village where dinner is at half seven."),
 F("Morning", "Santa Giulia's lagoon first — shallow, translucent, and empty at nine. Then Palombaggia and Tamaricciu for red rocks and umbrella pines."),
 F("Parking", "All of them fill by ten in August. Early or not at all."),
 F("Lunch", "Porto-Vecchio's walled upper town."),
 F("Afternoon", "Climb the D368 into the Ospedale forest — pines, granite boulders and fifteen degrees off the temperature. Piscia di Gallu is a 3.5 km round trip over slabs to a 60 m fall. Proper shoes."),
 F("By 18:30", "On to Zonza and check in. L'Aiglon serves dinner at half seven, so do not dawdle on the last stretch.", True),
 F("Evening", "Wild boar, chestnut, river trout, a log fire out of season."),
],
13: [
 F("Early", "Bavella at first light is the best hour of the trip, and afternoon storms build here from about two."),
 F("Morning", "Twenty minutes up the D268 to the Col de Bavella: seven red granite needles, some 1,800 m, wind-twisted pines and pigs on the road."),
 F("The hike", "Trou de la Bombe — 6 km, 300 m, two and a half hours — or the Alpine GR20 variant on fixed chains, 12 km and 1,000 m in about four hours. Either way, be down by two."),
 F("Optional first", "If you would rather not hike: Cucuruzzu near Levie, a Bronze Age fort in an oak wood, and Carbini's banded Romanesque church standing alone in its field."),
 F("Lunch", "The auberge at the col, or a picnic under the needles."),
 F("Afternoon", "Down the hairpins to Solenzara, then north up the coast to Aleria — Greek, then Roman, then capital of the province. Oysters on the Étang de Diane if there is time."),
 F("By 18:00", "West to Corte and check in. Book the Restonica shuttle tonight in the M-Ticket Via Corsica app.", True),
],
14: [
 F("Before light", "The hardest day. Head torch, 2–3 litres each, food, windproof layer."),
 F("First shuttle", "Navetta C13 from Corte station to A Frasseta, €4 return, booked last night. There is no other way up — the D623 has been shut beyond the Pont de Tragone since 2023.", True),
 F("Morning", "Walk the broken road up the valley — collapsed bridges, shattered tarmac — to the abandoned Bergeries de Grotelle, where one bar still opens daily."),
 F("Midday", "The climb proper: chains and rock steps to Lac de Melo at 1,711 m, then forty-five steeper minutes to Capitello if you have it. Turn back whenever you like."),
 F("Afternoon", "Back down. Eight hours door to door is normal for this."),
 F("Evening", "No move — you are already checked in, which is why this day sits where it does. Corte's citadel if your legs allow, dinner in the old town if they do not."),
],
15: [
 F("Check out by eleven", "Last drive. It is a good one."),
 F("Morning", "The Scala di Santa Regina: a bare red granite gorge cut by the Golo, with the old mule staircase across the water."),
 F("Late morning", "Lac de Calacuccia — turquoise, with the 2,706 m wall of Monte Cinto behind it. Swim near the bridge."),
 F("Midday", "The Canyon di A Ruda below the lake: sculpted chutes and pools, and a single-track road through the ravine. Lunch in Calacuccia village."),
 F("Afternoon", "North and east to Bastia. Ninety minutes."),
 F("By 18:00", "Check in — same hotel as night one, and fifteen minutes from the ferry.", True),
 F("Evening", "Last dinner in the old town. Nothing depends on tomorrow."),
],
16: [
 F("The buffer", "If everything ran to plan, today is a gift. If it did not — a closed road, a storm, a car in a garage — this is the day that absorbed it and you still sail."),
 F("Morning, if all is well", "The D71 into the Castagniccia: chestnut forest, half-empty hill villages, and the roofless Couvent d'Orezza, founded 1485 and abandoned at the Revolution. Narrow and slow; allow twice the map's time."),
 F("Lunch", "A terrace somewhere. The last one."),
 F("Afternoon", "Back to Bastia. Fuel, return the hire car if that is the plan, and buy the charcuterie and wine you kept meaning to."),
 F("Ferry check-in", "Two hours before sailing with a vehicle, an hour on foot. Booking on paper as well as phone.", True),
],
}
